TLMultimarcas/Controllers/AdministrativoFuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TLMultimarcas.Models;

namespace TLMultimarcas.Controllers
{
    public class AdministrativoFuncionariosController : Controller
    {
        private TLMultimarcasEntities db = new TLMultimarcasEntities();

        public ActionResult Funcionarios()
        {
            var users = db.Usuario;
            return View(users);
        }

        public ActionResult AdicionarFuncionario()
        {
            ViewBag.NomeFuncionario = new SelectList(db.Usuario, "NomeFuncionario");
            ViewBag.LoginFuncionario = new SelectList(db.Usuario, "LoginFuncionario");
            ViewBag.SenhaFuncionario = new SelectList(db.Usuario, "SenhaFuncionario");
            ViewBag.EmailFuncionario = new SelectList(db.Usuario, "EmailFuncionario");
            ViewBag.AdicionarFuncionario = new SelectList(db.Usuario, "AdicionarFuncionario");
            ViewBag.AdicionarVeiculo = new SelectList(db.Usuario, "AdicionarVeiculo");
            ViewBag.EditarFuncionario = new SelectList(db.Usuario, "EditarFuncionario");
            ViewBag.EditarVeiculo = new SelectList(db.Usuario, "EditarVeiculo");
            ViewBag.ExcluirFuncionario = new SelectList(db.Usuario, "ExcluirFuncionario");
            ViewBag.ExcluirVeiculo = new SelectList(db.Usuario, "ExcluirVeiculo");
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarFuncionarios(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NomeFuncionario = new SelectList(db.Usuario, "NomeFuncionario", usuario.NomeFuncionario);
            ViewBag.LoginFuncionario = new SelectList(db.Usuario, "LoginFuncionario", usuario.LoginFuncionario);
            ViewBag.SenhaFuncionario = new SelectList(db.Usuario, "SenhaFuncionario", usuario.SenhaFuncionario);
            ViewBag.EmailFuncionario = new SelectList(db.Usuario, "EmailFuncionario", usuario.EmailFuncionario);
            ViewBag.AdicionarFuncionario = new SelectList(db.Usuario, "AdicionarFuncionario");
            ViewBag.AdicionarVeiculo = new SelectList(db.Usuario, "AdicionarVeiculo");
            ViewBag.EditarFuncionario = new SelectList(db.Usuario, "EditarFuncionario");
            ViewBag.EditarVeiculo = new SelectList(db.Usuario, "EditarVeiculo");
            ViewBag.ExcluirFuncionario = new SelectList(db.Usuario, "ExcluirFuncionario");
            ViewBag.ExcluirVeiculo = new SelectList(db.Usuario, "ExcluirVeiculo");
            return View(usuario);
        }
    }
}

TLMultimarcas/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TLMultimarcas.Models;

namespace TLMultimarcas.Controllers
{
    public class FuncionariosController : Controller
    {
        private TLMultimarcasEntities db = new TLMultimarcasEntities();

        public ActionResult Index()
        {
            var users = db.Usuario;
            return View(users);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        public ActionResult Editar(long id)
        {
            Usuario usuario = db.Usuario.SingleOrDefault(m => m.IdUsuario == id);
            return View(usuario);
        }

        [HttpPost]
        public ActionResult Editar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        [HttpPost]
        public string Excluir(long id)
        {
            try
            {
                Usuario usuario = db.Usuario.Find(id);
                db.Usuario.Remove(usuario);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }

    }
}

TLMultimarcas/Views/AdministrativoFuncionarios/AdicionarFuncionario.cshtml
@model TLMultimarcas.Models.Usuario

@{
    ViewBag.Title = "AdicionarFuncionario";
}

<h2>AdicionarFuncionario</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoginFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenhaFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenhaFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenhaFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdicionarFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdicionarFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdicionarFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdicionarVeiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdicionarVeiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdicionarVeiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditarFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EditarFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EditarFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditarVeiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EditarVeiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EditarVeiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExcluirFuncionario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExcluirFuncionario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExcluirFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExcluirVeiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExcluirVeiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExcluirVeiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Funcionarios")
</div>

TLMultimarcas/Views/AdministrativoFuncionarios/Funcionarios.cshtml
@model IEnumerable<TLMultimarcas.Models.Usuario>

@{
    ViewBag.Title = "Funcionarios";
}

<h2>Funcionarios</h2>

<p>
    @Html.ActionLink("Adicionar", "AdicionarFuncionario")
</p>
<table class="table">
    <tr>
        <th>
            Nome do Funcionário
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.LoginFuncionario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SenhaFuncionario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailFuncionario)
        </th>*@
        <th>
            Adicionar Veículo
        </th>
        <th>
            Editar Veículo
        </th>
        <th>
            Excluir Veículo
        </th>
        <th>
            Adicionar Funcionário
        </th>
        <th>
            Editar Funcionário
        </th>
        <th>
            Excluir Funcionário
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(model => item.NomeFuncionario)
        </td>
        @*<td>
            @Html.DisplayFor(model => item.LoginFuncionario)
        </td>
        <td>
            @Html.DisplayFor(model => item.SenhaFuncionario)
        </td>
        <td>
            @Html.DisplayFor(model => item.EmailFuncionario)
        </td>*@
        <td>
            @Html.DisplayFor(model => item.AdicionarVeiculo)
        </td>
        <td>
            @Html.DisplayFor(model => item.EditarVeiculo)
        </td>
        <td>
            @Html.DisplayFor(model => item.ExcluirVeiculo)
        </td>
        <td>
            @Html.DisplayFor(model => item.AdicionarFuncionario)
        </td>
        <td>
            @Html.DisplayFor(model => item.EditarFuncionario)
        </td>
        <td>
            @Html.DisplayFor(model => item.ExcluirFuncionario)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Excluir", "Excluir", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>